machinehealthcheck:
  enabled: false

addons:
  cni: {}
  ccm: {}
  metallb: {}
  ingress: {}
  certmanager: {}
  csi: {}

certmanager: {}
csi: {}

# Allow to change default network CIDR.
# There is a lot of logic behind so for now you can only change
# the default 10.0.0.0/16 network by changing the second bit. For
# example setting `networkId: 123` would create network and routes
# for CIDR 10.123.0.0/16.
# WARNING: Please remember "10.96.0.0/12" and "10.42.0.0/16" are reserved by default.
networkId: 0

#dockerConfig:
#  registry: https://index.docker.io/v1/
#  auth: base64(docker_login:docker_password)
#
#
# outscale
#sshkeyname: REPLACE_MY_KEY
#multiaz: false
#region: eu-west-2            # Mandatory if multiaz: true
#subregionName: "eu-west-2a"  # Ignored if multiaz: true
#
#bastion:
#  enable: false
#loadbalancername: my-lb
apiAllowedCidr:
  - 0.0.0.0/0
# To reuse NATPublic IP, use tag OscK8sIPPool on IP matching the name you need
#natPublicIpPool: my-public-nat-pool
#controlplane:
#  version: v1.29.5
#  replicas: 1
#  vmType: tinav5.c2r4p3
#  subregionName: eu-west-2a
### choose on the key below : image or imageId, not both
#  image: ubuntu-22.04-2204-kubernetes-v1.29.1-2024-02-19
#  imageId: ami-554cf763
#  tags:
#    tags.osc.fcu.repulse_server: vm-control-plane
#  rootDisk:
#    rootDiskIops: 100
#    rootDiskSize: 30
#    rootDiskType: standard
#  volumes:
#    - name: data-volume
#      size: 10
#      iops: 100
#      volumeType: standard
#      subregionName: eu-west-2a
#workers:
#  - name: md-0
#    version: v1.29.5
#    replicas: 0
#    vmType: tinav5.c2r4p3
#    subregionName: eu-west-2a
### choose on the key below : image or imageId, not both
#    image: ubuntu-22.04-2204-kubernetes-v1.29.1-2024-02-19
#    imageId: ami-554cf763
#    tags:
#      tags.osc.fcu.repulse_server: vm-worker-md-0
#    rootDisk:
#      rootDiskIops: 100
#      rootDiskSize: 30
#      rootDiskType: standard
#
# credentials for ccm
#
osc_ccm_credentials: {}
#osc_ccm_credentials:
#  secret_key: ""
#  access_key: ""
#  region: ""
# credentials for csi
#
osc_csi_credentials: {}
#osc_csi_credentials:
#  access_key: ""
#  secret_key: ""

# Instead of creating the secret create an external-secret resource
# to provision the secret.
externalSecret:
  enabled: false
  tenant: opicloud-dev-osc-euw2
  secretStoreType: ClusterSecretStore
  secretStoreName: openbao-ppr
  refreshInterval: 1h0m0s
  mgmtClusterName: opicloud-dev-osc-euw2-mgmt-01
