# Default values for capi-cluster/outscale.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# clusterClass:
#   # name of the clusterclass to use
#   # this is the concatenatikon of:
#   #  - provider name
#   #  - "-v"
#   #  - the version of the helm chart "capi-clusterclass" which deployed
#   #    the clusterclass
#   name: outscale-v1.0.0

#   # Kubernetes version to use
#   # /!\ this must be in sync' with clusterClass.variables.vmImageName
#   kubernetesVersion: v1.28.5

#   # number of ControlPlane nodes
#   controlPlane:
#     replicas: 1
  
#   # list of MachineDeployments to implement
#   # along with their properties
#   workers:
#     machineDeployments:
#       - name: md-1
#         class: az1-md-class
#         replicas: 1

#   # variables to be passed into the clusterclass
#   variables:
#     coreDNSVersion: "v1.10.1"
#     vmImageName: "ubuntu-2204-2204-kubernetes-v1.28.5-2024-01-10"
#     controlPlane:
#       vmSize: tinav5.c4r8p2
#     workers:
#       vmSize: tinav5.c4r8p3
