---
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
    ## install first, and delete at the end
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "-1"
    # For Argo, this resource should be pruned last out of everything
    argocd.argoproj.io/sync-options: PruneLast=true
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-ccm-openstack-config
  namespace: default
stringData:
  cloudConf: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: cloud-config
      namespace: kube-system
    stringData:
      cloud.conf: |
        [Global]
        {{- range $key, $value := .Values.cloudConfig.cloudConf.global }}
        {{ $key }}={{ $value }}
        {{- end }}
        {{- range $section, $map := .Values.cloudConfig.cloudConf }}
          {{- if ne $section "global" }}
        [{{ $section }}]
            {{- range $key, $value := $map }}
        {{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
        {{- end }}

---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-ccm-openstack-config
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-ccm-openstack-config
  strategy: Reconcile
