{{/* iterate over the workers */}}
{{- range $name, $pool := .Values.workers }}
  {{- $generatedName := include "openstack.generatedName" (dict
    "clusterName" $.Values.global.clusterName
    "nodeType" "worker"
    "poolName" $name
    "kubeVersion" $pool.version
    "imageId" $pool.image
  ) }}

{{/* generates object */}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $.Values.global.clusterName }}-{{ $name }}
spec:
  clusterName: {{ $.Values.global.clusterName }}
  replicas: {{ $pool.replicas | default 0 }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $.Values.global.clusterName }}-{{ $name }}
      clusterName: {{ $.Values.global.clusterName }}
      {{- if $pool.failureDomain }}
      failureDomain: {{ $pool.failureDomain }}
      {{- end }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: {{ $generatedName }}
      version: {{ $pool.version }}
---
{{- end }}
