{{/* Common initialization */}}
{{- $generatedName := include "openstack.generatedName" (dict
    "clusterName" .Values.global.clusterName
    "nodeType" "cp"
    "kubeVersion" .Values.controlplane.version
    "imageId" .Values.controlplane.image
  ) }}

{{/* generates object */}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ $generatedName }}
  namespace: default
  labels:
    cluster-name: {{ .Values.global.clusterName }}
    node-type: "control-plane"
    kube-version:  {{ .Values.controlplane.version }}
    image-name:  {{ .Values.controlplane.image }}
spec:
  template:
    spec:
      configDrive: true
      {{- with $.Values.controlplane.serverGroup }}
      serverGroup: {{- toYaml . | nindent 8 }}
      {{- end }}
      flavor: {{ .Values.controlplane.flavor }}
      image:
        filter:
          name: {{ .Values.controlplane.image }}
      sshKeyName: {{ .Values.sshkeyname }}
      ports:
        - network:
            filter:
              name: {{ .Values.controlplane.network }}
          fixedIPs:
            - subnet:
                filter:
                  name: {{ .Values.controlplane.subnet | default "controlplane" }}
          allowedAddressPairs:
            - ipAddress: {{ .Values.controlplane.apiServerVirtualIP | default .Values.controlplane.apiServerFixedIP }}
      {{- if .Values.controlplane.rootVolume }}
      rootVolume:
        sizeGiB: {{ .Values.controlplane.rootVolume.sizeGiB }}
        type: {{ .Values.controlplane.rootVolume.type }}
      {{- end }}
