{{/* iterate over the workers */}}
{{- range $name, $pool := .Values.workers }}
  {{- $generatedName := include "openstack.generatedName" (dict
    "clusterName" $.Values.global.clusterName
    "nodeType" "worker"
    "poolName" $name
    "kubeVersion" $pool.version
    "imageId" $pool.image
  ) }}

{{/* generates object */}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ $generatedName }}
  labels:
    cluster-name: {{ $.Values.global.clusterName }}
    node-type: "worker"
    pool-name: {{ $name }}
    kube-version: {{ $pool.version }}
    image-name: {{ $pool.image }}
spec:
  template:
    spec:
      configDrive: true
      {{- with $pool.serverMetadata }}
      serverMetadata: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $pool.serverGroup }}
      serverGroup: {{- toYaml . | nindent 8 }}
      {{- end }}
      flavor: {{ $pool.flavor }}
      image:
        filter:
          name: {{ $pool.image }}
      sshKeyName: {{ $.Values.sshkeyname }}
      ports:
        - network:
            filter:
              name: {{ $pool.network }}
          fixedIPs:
            - subnet:
                filter:
                  name: {{ $pool.subnet | default "workers" }}
          allowedAddressPairs:
            - ipAddress: {{ $pool.ingressServerFixedIP }}
      {{- if $pool.rootVolume }}
      rootVolume:
        sizeGiB: {{ $pool.rootVolume.sizeGiB }}
        type: {{ $pool.rootVolume.type }}
      {{- end }}
      {{- if $pool.additionalBlockDevices }}
      additionalBlockDevices:
        - name: {{ $pool.additionalBlockDevices.name }}
          sizeGiB: {{ $pool.additionalBlockDevices.sizeGiB }}
          storage:
            type: Volume
            volume:
              type: {{ $pool.additionalBlockDevices.type }}
      {{- end }}
---
{{- end }}
