{{- if .Values.dockerConfig }}
---
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: {{ include "outscale.name" . }}-docker-config
  namespace: {{ .Values.global.clusterName | default "clusterNameIsNotDefined" }}
stringData:
  dockerconfigjson: |-
    apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: regcred
      namespace: kube-system
    stringData:
      .dockerconfigjson: >-
        {
          "auths": {
            "{{ .Values.dockerConfig.registry }}": {
              "auth": "{{ .Values.dockerConfig.auth }}"
            }
          }
        }
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ include "outscale.name" . }}-docker-config
  namespace: {{ .Values.global.clusterName | default "clusterNameIsNotDefined" }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName | default "clusterNameIsNotDefined" }}
  resources:
  - kind: Secret
    name: {{ include "outscale.name" . }}-docker-config
  strategy: Reconcile
{{- end }}
