{{- $values := .Values }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: {{ include "outscale.name" $ }}
  namespace: {{ .Values.global.clusterName | default "clusterNameIsNotDefined" }}
  labels:
    {{- include "outscale.labels" $ | nindent 4 }}
spec:
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OscClusterTemplate
      name: {{ include "outscale.name" . }}

  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: {{ include "outscale.name" $ }}
    namingStrategy:
      template: {{`"{{ .cluster.name }}-control-plane-{{ .random }}"`}}
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OscMachineTemplate
        name: {{ include "outscale.name" $ }}-controlplane
    machineHealthCheck:
      maxUnhealthy: 100%
      nodeStartupTimeout: 20m0s
      unhealthyConditions:
        - type: Ready
          status: Unknown
          timeout: 5m0s
        - type: Ready
          status: "False"
          timeout: 20m0s
        - status: "True"
          timeout: 1m0s
          type: DiskPressure

  workers:
    machineDeployments:
      {{- range $name, $_ := .Values.workers }}
      - class: {{ $name }}
        strategy:
          rollingUpdate:
            maxSurge: "20%"
            maxUnavailable: 0
          type: RollingUpdate
        namingStrategy:
          template: {{`"{{ .machineDeployment.topologyName }}-{{ .random }}"`}}
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: {{ include "outscale.name" $ }}
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: OscMachineTemplate
              name: {{ include "outscale.name" $ }}-worker-{{ $name }}
          metadata: {}
        machineHealthCheck:
          maxUnhealthy: 100%
          nodeStartupTimeout: 20m0s
          unhealthyConditions:
            - type: Ready
              status: Unknown
              timeout: 5m0s
            - type: Ready
              status: "False"
              timeout: 20m0s
            - status: "True"
              timeout: 1m0s
              type: DiskPressure
      {{- end }}

  variables:
    - name: coreDNSVersion
      # coredns is not upgraded automaticaly by cluster api
      # We need to specify the target version for each cluster/clusterclass
      # see https://github.com/kubernetes-sigs/cluster-api/issues/6429
      # and for default version for each kubernets versions:
      # https://github.com/kubernetes/kubernetes/blob/v1.28.5/cmd/kubeadm/app/constants/constants.go#L344
      required: true
      schema:
        openAPIV3Schema:
          type: string
          description: coredns image version (corends is not upgraded automaticaly by cluster api)
    - name: vmImageName
      required: true
      schema:
        openAPIV3Schema:
          type: string
          description: name iof the mage to use to provision controlplane and worker VMs
    - name: controlPlane
      required: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            vmSize:
              type: string
              description: size of the controlplane VMs
          required:
            - vmSize
    - name: workers
      required: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            vmSize:
              type: string
              description: size of the worker VMs
          required:
            - vmSize

  patches:
    # KubeadmControlPlaneTemplate patches
    - name: kcpt_main
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: KubeadmControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/dns/imageTag
              valueFrom:
                template: {{`"{{ .coreDNSVersion }}"`}}

    # OscMachineTemplate (ControlPlane) patches
    - name: omt_controlplane_main
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: OscMachineTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/node/image/name
              valueFrom:
                template: {{`"{{ .vmImageName }}"`}}
            - op: replace
              path: /spec/template/spec/node/vm/vmType
              valueFrom:
                template: {{`"{{ .controlPlane.vmSize }}"`}}

    # OscMachineTemplate (Workers) patches
    - name: omt_workers_main
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: OscMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  {{- range $name, $_ := .Values.workers }}
                  - {{ $name }}
                  {{- end }}
          jsonPatches:
            - op: replace
              path: /spec/template/spec/node/image/name
              valueFrom:
                template: {{`"{{ .vmImageName }}"`}}
            - op: replace
              path: /spec/template/spec/node/vm/vmType
              valueFrom:
                template: {{`"{{ .workers.vmSize }}"`}}
