---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: {{ include "outscale.name" . }}-controlplane
  namespace: default
  labels:
    {{- include "outscale.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      node:
        clusterName: "must-be-patched"
        image:
          name: "must-be-patched"
        keypair:
          name: "must-be-patched"
        vm:
          clusterName: "must-be-patched"
          keypairName: "must-be-patched"
          loadBalancerName: "must-be-patched"
          role: controlplane
          vmType: {{ .Values.controlplane.vmType | default "tinav5.c2r4p3"  }}
          # securityGroupNames: []
          {{- with .Values.controlplane.tags }}
          tags: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if hasKey .Values.controlplane "rootDisk" }}
          rootDisk:
            rootDiskIops: {{ .Values.controlplane.rootDisk.rootDiskIops | default 100 }}
            rootDiskSize: {{ .Values.controlplane.rootDisk.rootDiskSize | default 30 }}
            rootDiskType: {{ .Values.controlplane.rootDisk.rootDiskType | default "standard" }}
          {{- end }}
        {{- with .Values.controlplane.volumes }}
        volumes: {{- toYaml . | nindent 10 }}
        {{- end }}
