# Default values for capi-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

provider:
  openstack: false
  outscale: false

global:
  clusterName: my-cluster

  pods:
    cidrBlocks: "198.18.128.0/17"
  services:
    cidrBlocks: "198.18.0.0/17"
  
  # helmchartproxy installed inside workload cluster
  # helm addons
  addons:
    cni:
      enabled: true
      #type: calico
      #version: v3.27.3
      type: cilium
      version: 1.15.10
      config: {}
#        ipaddresspool:
#          layer: "l2"
#          name: "first-pool"
#          addresses:
#            - 192.168.101.11/32
    ccm:
      enabled: true
      type: outscale    # openstack
      version: 0.3.2    # 2.31.0
    csi:
      enabled: true
      type: osc-bsu-csi # cinder-csi
      version: 1.6.0    # 2.31.0
    metallb:
      enabled: false
      type: metallb
      version: 0.14.5
      #config:
      #  ipaddresspool:
      #    layer: "l2"
      #    name: "first-pool"
      #    addresses:
      #      - 192.168.101.11/32
    ingress:
      enabled: false
      type: ingress-nginx
      version: 4.10.1
    certmanager:
      enabled: false
      type: cert-manager
      version: v1.14.5
    storagelocal:
      enabled: false

#
# reference to openstack helm values
#
openstack: {}
#  machinehealthcheck:
#    enabled: false
#  sshkeyname: REPLACE_SSH_KEY_NAME_
#  router: router_services
#  network: network_kube
#  subnet: subnet_kube
#  bastion:
#    enabled: false
#    image: ubuntu22.04
#    flavor: CO1.2
#  controlplane:
#    version: v1.29.4
#    replicas: 1
#    image: ubuntu-2204-kube-v1.29.4
#    flavor: CO1.2
#    availabilityZones:
#      - AZ1
#      - AZ2
#    # reserved ip/port outside cluster-api
#    apiServerFixedIP: 192.168.101.10
#    #rootVolume: {}
#  workers:
#    md-0:
#      version: v1.29.4
#      replicas: 0
#      image: ubuntu-2204-kube-v1.29.4
#      flavor: CO1.2
#      # reserved ip/port outside cluster-api
#      ingressServerFixedIP: 192.168.101.11
#      #rootVolume: {}
##
## openstack cloud config
##
##  cloudConfig:
##    # used by ccm-openstack
##    cloudConf:
##      global:
##        auth-url: _OS_AUTH_URL/v3_
##        application-credential-id=_OS_APPLICATION_CREDENTIAL_ID_
##        application-credential-secret=_OS_APPLICATION_CREDENTIAL_SECRET_
##        region: "__OS_REGION_NAME_"
##    # used by cluster api provider openstack (capo)
##    cacert: _REPLACE_WITH_B64ENCODED_CACERT_
##    cloudsYaml: _REPLACE_WITH_B64_cloud.yaml_
#
##  dockerConfig:
#     registry: https://index.docker.io/v1/
#     auth: base64(docker_login:docker_password)

#
# reference to outscale helm values
# Note: the structure of these values is quiete different from openstack
#       values because outscale is now managed with 'ClusterClasses'
outscale: {}
  # clusterClass:
  #   # name of the clusterclass to use
  #   # this is the concatenatikon of:
  #   #  - provider name
  #   #  - "-v"
  #   #  - the version of the helm chart "capi-clusterclass" which deployed
  #   #    the clusterclass
  #   name: outscale-v1.0.0

  #   # Kubernetes version to use
  #   # /!\ this must be in sync' with clusterClass.variables.vmImageName
  #   kubernetesVersion: v1.28.5

  #   # number of ControlPlane nodes
  #   controlPlane:
  #     replicas: 1
    
  #   # list of MachineDeployments to implement
  #   # along with their properties
  #   workers:
  #     machineDeployments:
  #       - name: md-1
  #         class: az1-md-class
  #         replicas: 1

  #   # variables to be passed into the clusterclass
  #   variables:
  #     coreDNSVersion: "v1.10.1"
  #     vmImageName: "ubuntu-2204-2204-kubernetes-v1.28.5-2024-01-10"
  #     controlPlane:
  #       vmSize: tinav5.c4r8p2
  #     workers:
  #       vmSize: tinav5.c4r8p3
