---
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.clusterName }}-ccm-outscale-config
  namespace: default
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreType }}
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.global.clusterName }}-ccm-outscale-config
    template:
      engineVersion: v2
      type: addons.cluster.x-k8s.io/resource-set
      metadata:
        annotations:
          note: generated
          "helm.sh/hook": "pre-install,post-delete"
          "helm.sh/hook-weight": "-1"
          argocd.argoproj.io/sync-options: PruneLast=true
        labels:
          type: generated
      data:
        OscCloudConf: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: osc-secret
            namespace: kube-system
          stringData:
            key_id: {{ `{{ .key_id }}` }}
            access_key: {{ `{{ .secret_key }}` }}
            aws_default_region: {{ `{{ .region }}` }}
            aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
            osc_account_id: MY_OSC_ACCOUNT_ID
            osc_account_iam: MY_OSC_ACCOUNT_IAM
            osc_user_id: MY_OSC_USER_ID
            osc_arn: MY_OSC_ARN
  data:
  - secretKey: key_id
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: access_key
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/osc_ccm_credentials
  - secretKey: secret_key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: secret_key
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/osc_ccm_credentials
  - secretKey: region
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: region
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/osc_ccm_credentials
{{- else }}
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
    #"helm.sh/resource-policy": "keep"
    ## install first, and delete at the end
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "-1"
    # For Argo, this resource should be pruned last out of everything
    argocd.argoproj.io/sync-options: PruneLast=true
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-ccm-outscale-config
  namespace: default
stringData:
  OscCloudConf: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: osc-secret
      namespace: kube-system
    stringData:
      key_id: {{ .Values.osc_ccm_credentials.access_key }}
      access_key: {{ .Values.osc_ccm_credentials.secret_key }}
      aws_default_region: {{ .Values.osc_ccm_credentials.region }}
      aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
      osc_account_id: MY_OSC_ACCOUNT_ID
      osc_account_iam: MY_OSC_ACCOUNT_IAM
      osc_user_id: MY_OSC_USER_ID
      osc_arn: MY_OSC_ARN
{{ end }}
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-ccm-outscale-config
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-ccm-outscale-config
  strategy: Reconcile
