---
{{ if .Values.dockerConfig -}}
#
#  ClusterResourceSet: addconfiguration in workload cluster
#
---
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.clusterName }}-docker-config
  namespace: default
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreType }}
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.global.clusterName }}-docker-config
    template:
      engineVersion: v2
      type: addons.cluster.x-k8s.io/resource-set
      metadata:
        annotations:
          note: generated
        labels:
          type: generated
      data:
        OscCsiConf: |-
          apiVersion: v1
          kind: Secret
          metadata:
            name: osc-bsu-csi
            namespace: kube-system
          stringData:
            access_key: {{ `{{ .access_key }}` }}
            secret_key: {{ `{{ .secret_key }}` }}
        dockerconfigjson: |-
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/dockerconfigjson
          metadata:
            name: regcred
            namespace: kube-system
          stringData:
            .dockerconfigjson: >-
              {
                "auths": {
                  "{{ `{{ .registry }}` }}": {
                    "auth": "{{ `{{ .auth }}` }}"
                  }
                }
              }
  data:
  - secretKey: registry
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: registry
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/dockerconfig
  - secretKey: auth
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: auth
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/dockerconfig
{{- else }}
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-docker-config
  namespace: default
stringData:
  dockerconfigjson: |-
    apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: regcred
      namespace: kube-system
    stringData:
      .dockerconfigjson: >-
        {
          "auths": {
            "{{ .Values.dockerConfig.registry }}": {
              "auth": "{{ .Values.dockerConfig.auth }}"
            }
          }
        }
{{- end }}
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-docker-config
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-docker-config
  strategy: Reconcile
{{ end -}}
