{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.clusterName }}-eso-secret
  namespace: default
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreType }}
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.global.clusterName }}-eso-secret
    template:
      engineVersion: v2
      type: addons.cluster.x-k8s.io/resource-set
      metadata:
        annotations:
          note: generated
          "helm.sh/hook": "pre-install,post-delete"
          "helm.sh/hook-weight": "-1"
          argocd.argoproj.io/sync-options: PruneLast=true
        labels:
          type: generated
      data:
        EsoSecret: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: openbao-approle
            namespace: external-secrets
          stringData:
            secret-id: {{ `{{ .secret_id }}` }}
  data:
  - secretKey: secret_id
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: secret_id
      key: {{ .Values.externalSecret.secretsPath.eso }}
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-eso-secret
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-eso-secret
  strategy: Reconcile
{{- end }}
