{{ if and .Values.global.addons.csi.enabled ( eq .Values.global.addons.csi.type "osc-bsu-csi" )  -}}
---
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.clusterName }}-csi-outscale-config
  namespace: default
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreType }}
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.global.clusterName }}-csi-outscale-config
    template:
      engineVersion: v2
      type: addons.cluster.x-k8s.io/resource-set
      metadata:
        annotations:
          note: generated
          "helm.sh/hook": "pre-install,post-delete"
          "helm.sh/hook-weight": "-1"
          argocd.argoproj.io/sync-options: PruneLast=true
        labels:
          type: generated
      data:
        OscCsiConf: |-
          apiVersion: v1
          kind: Secret
          metadata:
            name: osc-bsu-csi
            namespace: kube-system
          stringData:
            access_key: {{ `{{ .access_key }}` }}
            secret_key: {{ `{{ .secret_key }}` }}
  data:
  - secretKey: secret_key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: secret_key
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/osc_csi_credentials
  - secretKey: access_key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: access_key
      key: k8s/tenant/{{ .Values.externalSecret.tenant }}/osc_csi_credentials
{{- else }}
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
    #"helm.sh/resource-policy": "keep"
    ## install first, and delete at the end
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "-1"
    # For Argo, this resource should be pruned last out of everything
    argocd.argoproj.io/sync-options: PruneLast=true
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-csi-outscale-config
  namespace: default
stringData:
  OscCsiConf: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: osc-bsu-csi
      namespace: kube-system
    stringData:
      access_key: {{ .Values.osc_csi_credentials.access_key }}
      secret_key: {{ .Values.osc_csi_credentials.secret_key }}
{{- end }}
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-csi-outscale-config
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-csi-outscale-config
  strategy: Reconcile
{{ end -}}
