{{ if .Values.machinehealthcheck.enabled -}}
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: {{ .Values.global.clusterName }}-node-unhealthy-5m
spec:
  clusterName: {{ .Values.global.clusterName }}
  remediation:
    triggerIf:
      unhealthyLessThanOrEqualTo: 100%
  checks:
    nodeStartupTimeoutSeconds: 600
    unhealthyNodeConditions:
    - status: Unknown
      timeoutSeconds: 300
      type: Ready
    - status: "False"
      timeoutSeconds: 300
      type: Ready
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.global.clusterName }}
{{ end -}}
