{{- $values := .Values }}
{{- range $name, $pool := .Values.workers }}
{{- range (include "outscale.subregionsLabels" $values | fromYamlArray) }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $.Values.global.clusterName }}-{{ $name }}{{ if $.Values.multiaz }}-{{ . }}{{ end }}
spec:
  clusterName: {{ $.Values.global.clusterName }}
  {{- $context := dict "subregion" . "replicas" $pool.replicas "multiaz" $.Values.multiaz }}
  replicas: {{ include "outscale.computeReplicas" $context }}
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 1
  selector:
    matchLabels: null
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $.Values.global.clusterName }}-{{ $name }}
      clusterName: {{ $.Values.global.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OscMachineTemplate
        name: {{- $base := printf "%s-%s-%s" $.Values.global.clusterName $name $pool.version -}}
              {{- if $.Values.multiaz }}{{- $base = printf "%s-%s" $base . }}{{- end -}}
              {{- $hash := sha256sum $pool.image | trunc 8 -}}
              {{- printf "%s-%s" $base $hash | trunc 63 | indent 1 }}
      version: {{ $pool.version }}
{{- end }}
{{- end }}
