---
{{- include "outscale.validate" . }}
{{- /* define net and subnet ranges */ -}}
{{- /* net range */ -}}
{{- $net_range := printf "10.%s.0.0/16" ( toString .Values.networkId ) }}
{{- /* loadbalancer ranges */ -}}
{{- $loadbalancer_ranges := list (printf "10.%s.2.0/24" (toString .Values.networkId)) -}}
{{- if .Values.multiAZ }}
  {{- $loadbalancer_ranges = append $loadbalancer_ranges (printf "10.%s.5.0/24" (toString .Values.networkId)) -}}
  {{- $loadbalancer_ranges = append $loadbalancer_ranges (printf "10.%s.8.0/24" (toString .Values.networkId)) -}}
{{- end }}
{{- /* worker ranges */ -}}
{{- $worker_ranges := list (printf "10.%s.3.0/24" (toString .Values.networkId)) -}}
{{- if .Values.multiAZ }}
  {{- $worker_ranges = append $worker_ranges (printf "10.%s.6.0/24" (toString .Values.networkId)) -}}
  {{- $worker_ranges = append $worker_ranges (printf "10.%s.9.0/24" (toString .Values.networkId)) -}}
{{- end }}
{{- /* controlplane ranges */ -}}
{{- $controlplane_ranges := list (printf "10.%s.4.0/24" (toString .Values.networkId)) -}}
{{- if .Values.multiAZ }}
  {{- $controlplane_ranges = append $controlplane_ranges (printf "10.%s.7.0/24" (toString .Values.networkId)) -}}
  {{- $controlplane_ranges = append $controlplane_ranges (printf "10.%s.10.0/24" (toString .Values.networkId)) -}}
{{- end }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscCluster
metadata:
  name: {{ .Values.global.clusterName }}
spec:
  network:
    bastion:
      enable: {{ .Values.bastion.enable | default "false" }}
    {{- if .Values.bastion.enable }}
      name: {{ .Values.global.clusterName }}-vm-bastion
      keypairName: {{ .Values.sshkeyname }}
      vmType: {{ .Values.bastion.vmType }}
      {{ if hasKey .Values.bastion "image" -}}
      imageName: {{ .Values.bastion.image }}
      {{ end -}}
      {{ if hasKey .Values.bastion "imageId" -}}
      imageId: {{ .Values.bastion.imageId }}
      {{ end -}}
      deviceName: "/dev/sda1"
      {{ if hasKey .Values.bastion "rootDisk" -}}
      rootDisk:
        rootDiskIops: {{ .Values.bastion.rootDisk.rootDiskIops | default 100 }}
        rootDiskSize: {{ .Values.bastion.rootDisk.rootDiskSize | default 30 }}
        rootDiskType: {{ .Values.bastion.rootDisk.rootDiskType | default "standard" }}
      {{ end -}}
    {{- end }}
    loadBalancer:
      healthCheck:
        checkinterval: 30
        healthythreshold: 5
        port: 6443
        protocol: TCP
        timeout: 30
        unhealthythreshold: 5
      listener:
        backendport: 6443
        backendprotocol: TCP
        loadbalancerport: 6443
        loadbalancerprotocol: TCP
      loadbalancername: {{ template "outscale.defaultLoadbalancerName" $ }}
      loadbalancertype: internet-facing
    {{- if hasKey .Values "natPublicIpPool" }}
    natPublicIpPool: {{ .Values.natPublicIpPool }}
    {{- end }}
    natServices:
    {{- if .Values.multiaz }}
      - name: {{ .Values.global.clusterName }}-nat-a
        subregionName: {{ .Values.region }}a
      - name: {{ .Values.global.clusterName }}-nat-b
        subregionName: {{ .Values.region }}b
      - name: {{ .Values.global.clusterName }}-nat-c
        subregionName: {{ .Values.region }}c
    {{- else }}
      - name: {{ .Values.global.clusterName }}-nat-a
        subregionName: {{ .Values.subregionName  }}
    {{- end }}
    net:
      name: {{ .Values.global.clusterName }}-net
      ipRange: {{ $net_range }}
    subregions:
    {{- if .Values.multiaz }}
      - {{ .Values.region }}a
      - {{ .Values.region }}b
      - {{ .Values.region }}c
    {{- else }}
      - {{ .Values.subregionName  }}
    {{- end }}
    {{- if hasKey .Values "apiAllowedCidr" }}
    {{- if gt (len .Values.apiAllowedCidr) 0 }}
    # Restricting access to kube api cluster
    allowFromIPRanges:
    {{- range $cidr := .Values.apiAllowedCidr }}
      - {{ $cidr }}
    {{- end }}
    {{- end }}
    {{- end }}
    securityGroups:
    {{- if .Values.bastion.enable }}
    - description: Bastion securityGroup for {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-bastion
      authoritative: true
      roles:
        - bastion
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-bastion-all-out
        flow: Outbound # default outbound rule
        ipProtocol: "-1"
        fromPortRange: 1
        toPortRange: 65535
        ipRanges:
        - "0.0.0.0/0"
      {{- if hasKey .Values.bastion "allow_cidr" }}
      {{- if gt (len .Values.bastion.allow_cidr) 0 }}
      - name: {{ $.Values.global.clusterName }}-bastion-ssh
        flow: Inbound
        fromPortRange: 22
        toPortRange: 22
        ipProtocol: tcp
        ipRanges:
        {{- range $cidr := .Values.bastion.allow_cidr }}
          - {{ $cidr }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    - description: Worker securityGroup for {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-worker
      authoritative: true
      roles:
        - worker
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-worker-bgp
        flow: Inbound
        fromPortRange: 179
        toPortRange: 179
        ipProtocol: tcp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-worker-kubelet
        flow: Inbound
        fromPortRange: 10250
        toPortRange: 10250
        ipProtocol: tcp
        ipRanges:
{{ toYaml $controlplane_ranges | indent 10 }}
{{ toYaml $worker_ranges | indent 10 }}
      - name: {{ .Values.global.clusterName }}-worker-nodeip
        flow: Inbound
        fromPortRange: 30000
        toPortRange: 32767
        ipProtocol: tcp
        ipRanges:
{{ toYaml $controlplane_ranges | indent 10 }}
{{ toYaml $worker_ranges | indent 10 }}
    - description: Controlplane securityGroup for {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-controlplane
      authoritative: true
      roles:
        - controlplane
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-controlplane-bgp
        flow: Inbound
        fromPortRange: 179
        toPortRange: 179
        ipProtocol: tcp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-controlplane-api
        flow: Inbound
        fromPortRange: 6443
        toPortRange: 6443
        ipProtocol: tcp
        ipRanges:
{{ toYaml $loadbalancer_ranges | indent 10 }}
{{ toYaml $controlplane_ranges | indent 10 }}
{{ toYaml $worker_ranges | indent 10 }}
      - name: {{ .Values.global.clusterName }}-controlplane-nodeip
        flow: Inbound
        fromPortRange: 30000
        toPortRange: 32767
        ipProtocol: tcp
        ipRanges:
{{ toYaml $controlplane_ranges | indent 10 }}
{{ toYaml $worker_ranges | indent 10 }}
      - name: {{ .Values.global.clusterName }}-controlplane-etcd
        flow: Inbound
        fromPortRange: 2378
        toPortRange: 2380
        ipProtocol: tcp
        ipRanges:
{{ toYaml $controlplane_ranges | indent 10 }}
      - name: {{ .Values.global.clusterName }}-controlplane-kubelet
        flow: Inbound
        fromPortRange: 10250
        toPortRange: 10252
        ipProtocol: tcp
        ipRanges:
{{ toYaml $controlplane_ranges | indent 10 }}
    - description: LB securityGroup for {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-lb
      authoritative: true
      roles:
        - loadbalancer
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-lb-out
        flow: Outbound
        fromPortRange: 6443
        toPortRange: 6443
        ipProtocol: tcp
        ipRanges:
{{ toYaml $controlplane_ranges | indent 10 }}
    - description: Node securityGroup for {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-node
      authoritative: true
      roles:
        - worker
        - controlplane
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-node-all-out
        flow: Outbound # default outbound rule
        ipProtocol: "-1"
        fromPortRange: 1
        toPortRange: 65535
        ipRanges:
        - "0.0.0.0/0"
      - name: {{ .Values.global.clusterName }}-node-all-tcp
        flow: Inbound
        fromPortRange: 1
        toPortRange: 65535
        ipProtocol: tcp
        ipRanges:
          - {{ $net_range }}
      {{ if .Values.global.addons.spegel.enabled -}}
      # spegel
      - name: {{ .Values.global.clusterName }}-node-spegel
        flow: Inbound
        fromPortRange: 5001
        toPortRange: 5001
        ipProtocol: tcp
        ipRanges:
          - {{ $net_range }}
      {{ end -}}
      - name: {{ .Values.global.clusterName }}-node-calico-vxlan
        flow: Inbound
        fromPortRange: 4789
        toPortRange: 4789
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-typha
        flow: Inbound
        fromPortRange: 5473
        toPortRange: 5473
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-wireguard
        flow: Inbound
        fromPortRange: 51820
        toPortRange: 51820
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-wireguard-ipv6
        flow: Inbound
        fromPortRange: 51821
        toPortRange: 51821
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-flannel
        flow: Inbound
        fromPortRange: 4789
        toPortRange: 4789
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-flannel-udp
        flow: Inbound
        fromPortRange: 8285
        toPortRange: 8285
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      # icmp
      - name: {{ .Values.global.clusterName }}-node-icmp
        flow: Inbound
        fromPortRange: 8
        toPortRange: 8
        ipProtocol: icmp
        ipRanges:
          - {{ $net_range }}
      # cilium
      - name: {{ .Values.global.clusterName }}-node-cilium-vxlan
        flow: Inbound
        fromPortRange: 8472
        toPortRange: 8472
        ipProtocol: udp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-cilium-health
        flow: Inbound
        fromPortRange: 4240
        toPortRange: 4240
        ipProtocol: tcp
        ipRanges:
          - {{ $net_range }}
      - name: {{ .Values.global.clusterName }}-node-cilium-hubble
        flow: Inbound
        fromPortRange: 4244
        toPortRange: 4244
        ipProtocol: tcp
        ipRanges:
          - {{ $net_range }}
      {{ if .Values.bastion.enable -}}
      - name: {{ .Values.global.clusterName }}-node-ssh
        flow: Inbound
        fromPortRange: 22
        toPortRange: 22
        ipProtocol: tcp
        ipRanges:
{{ toYaml $loadbalancer_ranges | indent 10 }}
      {{ end -}}
      tag: OscK8sMainSG
