{{- /* Common initialization */ -}}
{{- $generatedName := include "outscale.generatedName" (dict
    "clusterName" .Values.global.clusterName
    "nodeType" "cp"
    "kubeVersion" .Values.controlplane.version
    "imageId" .Values.controlplane.image
  ) }}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: {{ $generatedName }}
  labels:
    cluster-name: {{ .Values.global.clusterName }}
    node-type: "control-plane"
    kube-version:  {{ .Values.controlplane.version }}
    image-name:  {{ .Values.controlplane.image }}
spec:
  template:
    spec:
      node:
        clusterName: {{ .Values.global.clusterName }}
        {{- if hasKey .Values.controlplane "image" }}
        image:
          name: {{ .Values.controlplane.image }}
        {{- end }}
        keypair:
          name: {{ .Values.sshkeyname }}
        vm:
          clusterName: {{ .Values.global.clusterName }}
          keypairName: {{ .Values.sshkeyname }}
          loadBalancerName: {{ template "outscale.defaultLoadbalancerName" $ }}
          role: controlplane
          vmType: {{ .Values.controlplane.vmType }}
          {{- if hasKey .Values.controlplane "imageId" }}
          imageId: {{ .Values.controlplane.imageId }}
          {{- end }}
          {{- if not .Values.multiaz }}
          subregionName: {{ .Values.controlplane.subregionName  }}
          {{- end }}
          {{- $dict1 := .Values.controlplane.tags | default dict }}
          {{- $tags := merge $dict1 (include "outscale.kcpDefaultTags" . | fromYaml ) }}
          tags:
          {{- $tags | toYaml | nindent 12 }}
          {{- if hasKey .Values.controlplane "rootDisk" }}
          rootDisk:
            rootDiskIops: {{ .Values.controlplane.rootDisk.rootDiskIops | default 100 }}
            rootDiskSize: {{ .Values.controlplane.rootDisk.rootDiskSize | default 30 }}
            rootDiskType: {{ .Values.controlplane.rootDisk.rootDiskType | default "standard" }}
          {{- end }}
        {{- with .Values.controlplane.volumes }}
        volumes: {{- toYaml . | nindent 10 }}
        {{- end }}
