{{- /* Common initialization */ -}}
{{- $values := .Values }}

{{- range $name, $pool := $values.workers }}
  {{- $isMultiaz := $values.multiaz | default false }}
  {{- $subregions := (include "outscale.subregionsLabels" $values | fromYamlArray) }}
  {{- if not $isMultiaz }}
    {{- $subregions = list "" }}
  {{- end }}

  {{- range $subregion := $subregions }}
    {{- $poolName := $name }}
    {{- $subregionName := "" }}
    {{- $subnetName := "" }}

    {{- if $isMultiaz }}
      {{- $poolName = printf "%s-%s" $name $subregion }}
      {{- $subregionName = printf "%s%s" $values.region $subregion }}
      {{- $subnetName = printf "%s-subnet-kw-%s" $values.global.clusterName $subregion }}
    {{- else }}
      {{- $subregionName = $pool.subregionName }}
    {{- end }}

    {{- $generatedName := include "outscale.generatedName" (dict
      "clusterName" $values.global.clusterName
      "nodeType" "worker"
      "poolName" $poolName
      "kubeVersion" $pool.version
      "imageId" $pool.image
    ) }}

    {{- $tagsDefault := include "outscale.kwDefaultTags" (dict "ctx" $values "name" $name) | fromYaml }}
    {{- $tagsMerged := merge ($pool.tags | default dict) $tagsDefault }}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: {{ $generatedName }}
  labels:
    cluster-name: {{ $values.global.clusterName }}
    node-type: "worker"
    pool-name: {{ $poolName }}
    kube-version: {{ $pool.version }}
    image-name: {{ $pool.image }}
spec:
  template:
    spec:
      node:
        clusterName: {{ $values.global.clusterName }}
        {{- if hasKey $pool "image" }}
        image:
          name: {{ $pool.image }}
        {{- end }}
        keypair:
          name: {{ $values.sshkeyname }}
        vm:
          clusterName: {{ $values.global.clusterName }}
          keypairName: {{ $values.sshkeyname }}
          vmType: {{ $pool.vmType }}
          {{- if hasKey $pool "imageId" }}
          imageId: {{ $pool.imageId }}
          {{- end }}
          subregionName: {{ $subregionName }}
          {{- if $subnetName }}
          subnetName: {{ $subnetName }}
          {{- end }}
          tags:
{{ $tagsMerged | toYaml | indent 12 }}
          {{- if hasKey $pool "rootDisk" }}
          rootDisk:
            rootDiskIops: {{ $pool.rootDisk.rootDiskIops | default 100 }}
            rootDiskSize: {{ $pool.rootDisk.rootDiskSize | default 30 }}
            rootDiskType: {{ $pool.rootDisk.rootDiskType | default "standard" }}
          {{- end }}
        {{- with $pool.volumes }}
        volumes: {{ toYaml . | nindent 10 }}
        {{- end }}
  {{- end }}
{{- end }}
