# Default values for capi-clusterclasses.
# This is a YAML-formatted file.

# this is used in the helm chart to decide which subchart to enable
# see dependencies[].condition in Chart.yaml
provider:
  outscale: true

# values that are common to all providers
global:
  clusterName: my-cluster

# values that are specific to the provider 'outscale'
outscale:
  # maximum number of pods that can be scheduled on a node
  maxPods: 110

  # SSH keyname to be injected into the VMs for this cluster
  # (also used for the bastion if any)
  sshkeyname: k8s-infra

  # Name of the Outscale subregion to use to deploy resources that
  # do require subregion to be documented (bastion, subnets,
  # OscMachineTemplates dedicated one specific AZ)
  subregionName: eu-west-2a

  # properties of the bastion
  bastion:
    enable: false
    vmType: tinav5.c4r8p3
    image: ubuntu-2204-2204-kubernetes-v1.28.5-2024-01-10
    subregionName: eu-west-2a
    rootDisk:
      rootDiskIops: 1000
      rootDiskSize: 50
      rootDiskType: gp2
    allow_cidr:
      - 133.99.1.0/24
      - 216.168.2.123/32

  # properties of the controlplane
  controlplane:
    replicas: 1
    rootDisk:
      rootDiskIops: 1000
      rootDiskSize: 50
      rootDiskType: gp2

  # properties of the workers
  workers:
    # the names of these dictionaries will be used in the template 'ClusterClass.yaml'
    # as the names of the 'MachineDeployment classes'
    
    # for workers that will be *not* hosted in a specific availability zone
    regionwide-md-class:
      rootDisk:
        rootDiskIops: 1000
        rootDiskSize: 50
        rootDiskType: gp2

    # for workers that will be hosted in a specific availability zone
    # note that the name 'az1' is irrelevent, it could be anything
    az1-md-class:
      subregionName: eu-west-2a
      rootDisk:
        rootDiskIops: 1000
        rootDiskSize: 50
        rootDiskType: gp2

    # for workers that will be hosted in a specific availability zone
    # note that the name 'az2' is irrelevent, it could be anything
    az2-md-class:
      subregionName: eu-west-2b
      rootDisk:
        rootDiskIops: 1000
        rootDiskSize: 50
        rootDiskType: gp2

  # list of ClusterResourceSets to deploy
  # Note: the actual addons are deployed via "HelmsChartProxy" resources
  #       here, the CRS are used to deploy the secrets that are required
  #       by the addons
  addonsCrsSecrets:
    ccm:
      enabled: true
    csi:
      enabled: true

  # credentials for the Outscale CCM
  osc_ccm_credentials:
    access_key: "REDACTED"
    secret_key: "REDACTED"
    region: "eu-west-2"

  # credentials for the Outscale CSI driver
  osc_csi_credentials:
    access_key: "REDACTED"
    secret_key: "REDACTED"

  # credentials for docker.io
  # (to minimize the throttling when pulling anonymously)
  dockerConfig:
    registry: https://index.docker.io/v1/
    auth: "REDACTED"
