{{- $values := .Values }}
{{- range $name, $pool := .Values.workers }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ $.Values.global.clusterName }}-{{ $name }}-{{ $pool.version }}
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock
---
{{- end }}
